### ISSUE TITLE
Add option to hide console output.

### ISSUE THREAD

**Issue by mihaisava** [VGBenjamin/PackageInstaller#1]
Is it possible to add an option to hide the console output when running Sidewalk.SC.PackageInstaller.Client.exe ? Thanks

**Comment by VGBenjamin** [comment]
I can do it if needed but I think that the redirection of the output to null should do the same trick without any modifications. 

Something like:
In Powershell:
(Sidewalk.SC.PackageInstaller.Client.exe -sitecoreUrl "http://sc72rev140228" -sitecoreDeployFolder "C:\inetpub\wwwroot\sc72rev140228\Website" -packagePath "C:\temp\TestPkg.zip" -connector "sitecore") | out-null

In Batch:
(Sidewalk.SC.PackageInstaller.Client.exe -sitecoreUrl "http://sc72rev140228" -sitecoreDeployFolder "C:\inetpub\wwwroot\sc72rev140228\Website" -packagePath "C:\temp\TestPkg.zip" -connector "sitecore") > $null

Source:
http://stackoverflow.com/questions/5881174/redirecting-output-to-null-in-powershell-but-ensuring-the-variable-remains-set

Could you tell me if this can do the job for you?

**Comment by mihaisava** [comment]
It worked Yes! Thank You.
