### ISSUE TITLE
During deployment how items that are updated are treated?

### ISSUE THREAD

**Issue by mihaisava** [VGBenjamin/PackageInstaller#2]
Hello,

Let's say for example that I'm working on Item 1 with ID {100-000} and I'm deploying and installing this item.After 2 days I'm doing some updates tot his items and remove something from it. When I run the PackageInstaller what happens? It will overwrite with the new updated item?

**Comment by VGBenjamin** [comment]
This depend how you have build your package to install. 
I only use the Sitecore API for it so the functionalities stay the same. 

https://sdn.sitecore.net/upload/sitecore6/65/package_designer_admin_guide-a4.pdf
On page 30: the different option to override or not your items are explained.
