### ISSUE TITLE
Console failed after installation of items is completed.

### ISSUE THREAD

**Issue by mihaisava** [VGBenjamin/PackageInstaller#5]
Hello,

So after the sitecore items are done installing using the tools i'm getting the following

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
28-Jul-2016 12:17:05         at System.Console.ReadKey(Boolean intercept)
28-Jul-2016 12:17:05         at System.Console.ReadKey()
28-Jul-2016 12:17:05         at Sidewalk.SC.PackageInstaller.Client.Program.WaitIfNotDebug() in C:\Users\msava\Documents\PackageInstaller-master\Sidewalk.SC.PackageInstaller.Client\Program.cs:line 377
28-Jul-2016 12:17:05         at Sidewalk.SC.PackageInstaller.Client.Program.Main(String[] args) in C:\Users\msava\Documents\PackageInstaller-master\Sidewalk.SC.PackageInstaller.Client\Program.cs:line 367

Do you know what can cause this? I'm running the deployment via Atlassian Bamboo , If I run from CLI it works fine.

**Comment by VGBenjamin** [comment]
Did you compile the installer in release mode? If you still have the issue you could just remove the Console.ReadKey() and rebuild. It should do the trick
